from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from ._data import AgentProfileSpec, ROLE_OPTIONS, PERSONALITY_OPTIONS
from rich import box

from ._ui import console, ACCENT, Panel, Rule, _label_for


def render_preview(spec: AgentProfileSpec) -> str:
    lines: list[str] = []
    lines.append(f"{spec.avatar_emoji} {spec.display_name}")
    lines.append(f"Tagline: {spec.tagline}")
    lines.append("")
    lines.append("Interview summary:")
    lines.append(f"  User/context: {spec.user_context}")
    lines.append(f"  Outcomes:     {spec.intended_outcomes}")
    lines.append(f"  Environment:  {spec.operating_context}")
    lines.append(f"  Surfaces:     {', '.join(spec.target_platforms)}")
    if spec.source_idea_name:
        lines.append(f"  Started from: {spec.source_idea_name}")
    if spec.use_cases:
        lines.append(f"  Use cases:    {', '.join(spec.use_cases)}")
    lines.append("")
    lines.append(f"Profile: {spec.profile_name}")
    lines.append(f"Model:   {spec.model} via {spec.model_provider}")
    lines.append(f"Role:    {_label_for(spec.primary_role, ROLE_OPTIONS)}")
    if spec.secondary_roles:
        lines.append("Also:    " + ", ".join(spec.secondary_roles))
    lines.append(f"Personality: {_label_for(spec.personality, PERSONALITY_OPTIONS)}")
    lines.append(f"Tone:    {', '.join(spec.tones)}")
    lines.append("")
    lines.append("Skills:")
    if spec.skill_sets:
        for category, selected in spec.skill_sets.items():
            lines.append(f"  {category}: {', '.join(selected)}")
    if spec.custom_skills:
        lines.append("  Custom: " + ", ".join(spec.custom_skills))
    lines.append(f"  Total skills: {spec.total_skills}")
    lines.append("")
    lines.append("Response style:")
    lines.append(f"  Length:   {spec.response_length}")
    lines.append(f"  Emoji:    {spec.emoji_usage}")
    lines.append(f"  Fallback: {spec.fallback_behavior}")
    lines.append("")
    lines.append("Boundaries:")
    if spec.boundaries:
        for b in spec.boundaries:
            lines.append(f"  - {b}")
    if spec.blocked_topics:
        lines.append("  Blocked topics: " + ", ".join(spec.blocked_topics))
    return "\n".join(lines)


def print_preview(spec: AgentProfileSpec) -> None:
    console.print(Panel(render_preview(spec), title="Blueprint Preview", border_style=ACCENT, box=box.ROUNDED, padding=(1, 2)))


def generate_soul_md(spec: AgentProfileSpec) -> str:
    secondary = ", ".join(spec.secondary_roles) if spec.secondary_roles else "None"
    skills = []
    for category, selected in spec.skill_sets.items():
        skills.append(f"### {category}")
        skills.extend(f"- {s}" for s in selected)
    if spec.custom_skills:
        skills.append("### Custom skills")
        skills.extend(f"- {s}" for s in spec.custom_skills)
    skills_text = "\n".join(skills) if skills else "- No selected skill sets yet."
    boundaries = "\n".join(f"- {b}" for b in spec.boundaries) or "- Use good judgement and escalate uncertainty."
    if spec.blocked_topics:
        boundaries += "\n- Blocked topics: " + ", ".join(spec.blocked_topics)

    return f"""# {spec.avatar_emoji} {spec.display_name}

## Identity

I am {spec.display_name}.

{spec.tagline}

## Model context

Default backend reference: `{spec.model}` via `{spec.model_provider}`.

## User and operating context

Target user/context: {spec.user_context}
Intended outcomes: {spec.intended_outcomes}
Operating context: {spec.operating_context}
Target surfaces: {', '.join(spec.target_platforms)}

## Role

Primary role: `{spec.primary_role}`.
Secondary roles: {secondary}.

## Personality

Archetype: `{spec.personality}`.
Tone: {', '.join(spec.tones)}.

## Skills

{skills_text}

## Response preferences

- Length: {spec.response_length}
- Emoji usage: {spec.emoji_usage}
- Fallback behaviour: {spec.fallback_behavior}

## Boundaries and guardrails

{boundaries}

## Operating rule

Be useful, clear, and consistent with this profile. If a request conflicts with the boundaries above, explain the constraint briefly and offer a safe alternative.
"""


def generate_user_md(spec: AgentProfileSpec) -> str:
    return f"""# USER.md

This profile was generated by `hermes profile wizard` after a full interview.

## Intended agent

- Display name: {spec.display_name}
- Profile name: {spec.profile_name}
- Primary role: {spec.primary_role}
- Secondary roles: {', '.join(spec.secondary_roles) if spec.secondary_roles else 'None'}

## Interview context

- User/context: {spec.user_context}
- Intended outcomes: {spec.intended_outcomes}
- Operating context: {spec.operating_context}
- Target surfaces: {', '.join(spec.target_platforms)}

## Preferred interaction style

- Length: {spec.response_length}
- Emoji usage: {spec.emoji_usage}
- Tone: {', '.join(spec.tones)}
- Fallback: {spec.fallback_behavior}

## Notes

This file captures profile-level user expectations for this agent. Edit it manually as the profile evolves.
"""


def _description(spec: AgentProfileSpec) -> str:
    return (
        f"{spec.display_name}: {spec.primary_role.replace('_', ' ')} profile for "
        f"{spec.operating_context or 'Hermes'} with {spec.personality} personality, "
        f"{', '.join(spec.tones)} tone, and {spec.total_skills} selected skill(s)."
    )


def export_profile(spec: AgentProfileSpec, kind: str, output_dir: Path | None = None) -> Path | None:
    output_dir = output_dir or Path.cwd()
    output_dir.mkdir(parents=True, exist_ok=True)
    data = asdict(spec)
    if kind == "json":
        path = output_dir / f"{spec.profile_name}.profile.json"
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        return path
    if kind == "js":
        path = output_dir / f"{spec.profile_name}.profile.js"
        path.write_text("export default " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n", encoding="utf-8")
        return path
    if kind == "stdout":
        print(json.dumps(data, indent=2, ensure_ascii=False))
        return None
    return None
